<div class="box">
	<div class="title"><?php echo $title ?>
		<span style="color: rgba(0,0,0,0.5); font-size: 11px"> (<?php echo($users->total) ?>)</span>
	</div>
	<?php if($users): ?>
		<div class="box-content two-line-media clearfix">
			<?php foreach($users->results() as $user): ?>
				<?php if($user['id'] != $app->profileUser['id']): ?>
					<?php echo view('user/display', array('user' => $user)) ?>
				<?php endif; ?>
			<?php endforeach ?>
		</div>
		<div class="box-content">
			<?php echo $users->links(true) ?>
		</div>
	<?php else: ?>
		<div class="box-content">
			<div class="alert alert-info"><?php echo lang('no-members-to-display') ?></div>
		</div>
	<?php endif ?>
</div>